config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root "lists#index"

  resources :lists do
    resources :bookmarks, only: [ :new, :create ]
  end
  resources :movies, only: [ :index, :show ]
  resources :bookmarks, only: [ :destroy ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :list
  belongs_to :movie
  validates :comment, length: { minimum: 6 }
  validates :list, presence: true, uniqueness: { scope: :movie }
end

app/models/list.rb
class List < ApplicationRecord
  has_one_attached :photo
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, presence: true, uniqueness: true
  validate :photo_size

  private

  def photo_size
    if photo.attached? && photo.blob.byte_size > 5.megabytes
      errors.add(:photo, "should be less than 5MB")
      photo.purge  # Optionally purge the photo to prevent it from being saved
    end
  end
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  def new
    @movies = Movie.all
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(set_params)
    @list = List.find(params[:list_id])
    @bookmark.list = @list

    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def set_params
    params.require(:bookmark).permit(:comment, :movie_id, :list_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :define_list, only: ["show", "edit", "update", "destroy"]
  def index
    @lists = List.all
  end

  def show
    @movies = @list.movies
    @bookmarks = @list.bookmarks
    @movies_from_query = Movie.where("title LIKE ?", "%#{params[:query]}%")
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(params.require(:list).permit(:name, :photo))
    @list.save
    if @list.save
      redirect_to list_path(@list), notice: 'List created successfully.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
  end

  def destroy
    @list.destroy
    redirect_to lists_path
  end

  private

  def define_list
    @list = List.find(params[:id])
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/new.html.erb
<div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1478720568477-152d9b164e26?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fG1vdmllfGVufDB8fDB8fHww)">
  <%= link_to lists_path do%>
  <div class="back-btn">
    <i class="fa-solid fa-backward"></i>
  </div>
  <% end %>
  <h1 class="title"><%= @list.name %></h1>
</div>

<div class="p-5 d-flex justify-content-between flex-wrap gap-5">

<% @movies.each do |movie| %>
  <div class="card d-flex flex-wrap gap-4" style="width: 18rem;">
    <img src="<%= movie.poster_url %>" class="card-img-top" alt="...">
    <div class="card-body d-flex flex-column justify-content-between">
      <div>
        <h3 class="card-text"><%= movie.title %></h3>
        <p class="card-text"><%= movie.overview %></p>
      </div>

      <%= simple_form_for([@list, @bookmark]) do |f| %>
        <%= f.label :comment, label: "Add a bookmark:" %>
        <%= f.input :comment, label: false %>
        <%= f.hidden_field :movie_id, value: movie.id %>
        <%= f.button :submit, "Add Movie to #{@list.name}"  %>
      <% end %>
    </div>

  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/edit.html.erb
<div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1478720568477-152d9b164e26?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fG1vdmllfGVufDB8fDB8fHww)">
  <%= link_to lists_path do%>
  <div class="back-btn">
    <i class="fa-solid fa-backward"></i>
  </div>
  <% end %>
  <h1>Edit <%= @list.name %></h1>
</div>

app/views/lists/index.html.erb
<div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1478720568477-152d9b164e26?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fG1vdmllfGVufDB8fDB8fHww)">
  <%# <div class="back-btn">
    <i class="fa-solid fa-backward"></i>
  </div> %>
  <h1 class="title">My Lists</h1>
</div>


<div class="d-flex flex-wrap align-items-center gap-4 m-5">
  <% @lists.each do |list| %>
    <% image = list.photo.key ? list.photo.key : "../assets/images/default_photo.avif" %>
  <div class="list_card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path image, height: 300, crop: :fill%>')">
  <span class="d-inline-block" tabindex="0" data-bs-toggle="popover" data-bs-trigger="hover focus" data-bs-content="Disabled popover">
  <%= link_to list_path(list), class: "destroy-link", method: :delete, data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } do %>
      <i class="fa-solid fa-trash"></i>
    <% end %>
</span>


    <%= link_to list_path(list), class: "card-link" do %>
      <div>
        <h2 class="title"><%= list.name %></h2>
      </div>
    <% end %>
  </div>

  <% end %>
  <div>
   <%= link_to new_list_path, class: "btn btn-outline-primary" do %>
    <i class="fa-solid fa-plus"></i>
  <% end %>
  </div>
</div>

app/views/lists/new.html.erb
<div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1478720568477-152d9b164e26?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fG1vdmllfGVufDB8fDB8fHww)">
  <%= link_to lists_path do%>
  <div class="back-btn">
    <i class="fa-solid fa-backward"></i>
  </div>
  <% end %>
  <h1>Add a New List </h1>
</div>

<div class="form-container">
  <%= simple_form_for(@list) do |f| %>
    <%= f.label :name, label: "List name" %>
    <%= f.input :name, label: false %>
    <%= f.input :photo, as: :file, label: "Add a photo"%>
    <% if @list.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@list.errors.count, "error") %> prohibited this list from being saved:</h2>
        <ul>
          <% @list.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <%= f.submit %>
  <% end %>
</div>

app/views/lists/show.html.erb
<% image = @list.photo.key ? @list.photo.key : "../assets/images/default_photo.avif" %>
<div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path image,  crop: :fill%>')">
  <%= link_to lists_path do%>
  <div class="back-btn">
    <i class="fa-solid fa-backward"></i>
  </div>
  <% end %>
  <h1 class="title"><%= @list.name %></h1>
</div>

<div class="p-5 d-flex flex-wrap align-items-center gap-5">

  <% if @list.bookmarks.any? %>
  <% @list.bookmarks.each do |bookmark| %>
      <div class="card" style="width: 18rem;">
        <img src="<%= bookmark.movie.poster_url %>" class="card-img-top" alt="...">
        <div class="card-body">
          <h3><%= bookmark.movie.title %></h3>
          <p class="card-text"><%= bookmark.movie.overview %></p>
          <p class="card-text"><%= bookmark.comment %></p>
        </div>
      </div>
  <% end %>
<% else %>
  <h2 style="width:100%; color:gray;" class="text-center">You currently have no movies in this list</h2>
<% end %>
<%= link_to "Add a Movie", new_list_bookmark_path(@list), class: "btn btn-primary" %>
</div>


<%= link_to list_path(@list), method: :delete, data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } do %>
          <i class="fa-solid fa-trash"></i>
        <% end %>

<%# <%= cl_image_tag @list.photo.key, height: 300, width: 400, crop: :fill %>